services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bella-italia-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: bella-italia-nginx
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: bella-italia-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: